const ru = {
    aboutUs: "О Нас",
    team: "Команда",
    publications: "Публикаций",
    contacts: "Контакты",
    aboutUs_forecasting: "Система прогнозирования и поддержки развития",
    aboutUs_concept: "Концепция развития методической компетентности",
    aboutUs_rise: "Курсы повышения квалификации для преподавателей",
    aboutUs_course: "Система курсовой и посткурсовой поддержки",
    aboutUs_education: "Развитие IT-образования",
    aboutUs_practice: "Практические занятия",
    aboutUs_innovation: "Инновационный подход",
    aboutUs_software: "Программное и учебно-методическое обеспечение",
    banner1: "Концепция развития методических компетенций преподавателей IT дисциплин",
    banner2: "Система курсовой и посткурсовой поддержки преподавателей IT дисциплин",
    banner3: "Внедрение уровневых стандартов на основе профессионального стандарта \"Педагог\"",
    banner4: "Система прогнозирования и непрерывной поддержки развития методической компетенции преподавателей",
    education: "Образование",
    jobInformation: "Сведения о работе",
    generalInformation: "Общие сведения",
    email: "Почта",
    birthDate: "Дата рождения",
    university: "Унивеситет",
    graduationYear: "Год окончания",
    specialization: "Специальность",
    admissionDate: "Дата поступления",
    degreeAwarded: "Присвоенная степень",
    degree: "Степень",
    position: "Должность",
    rank: "Звание",
    disciplineNames: "Преподаваемые дисциплины",
    userNotFound: "Пользователь не найден",
    admin: "Админ",
    trainer: "Тренер",
    role: "Роль",
    password: "Пароль",
    confirmPassword: "Подтвердить пароль",
    username: "Имя пользователя"
}

const eng = {
    aboutUs: "About Us",
    team: "Team",
    publications: "Publications",
    contacts: "Contacts",
    levelCompetence: "Do you want to know the level of your competence?",
    projectTeam: "Project Team",
    noAccount: "I don't have an account",
    yesAccount: "I have an account",
    login: "Login",
    log_in: "Log in",
    register: "Register",
    dashboard: "Dashboard",
    coursesAll: "All courses",
    coursesMy: "My courses",
    postCoursesMy: "My post-courses",
    coursesPre: "Pre-courses",
    competenceMap: "Competence Map",
    myTasks: "My Tasks",
    chat: "Chat",
    chats: "Chats",
    calendar: "Calendar",
    setting: "Settings",
    logout: "Logout",
    error: "Error",
    problem: "Sorry, we have some problems",
    back: "Back",
    taskDone: "Task Done",
    lessons: "Lessons",
    sections: "Sections",
    section: "Section",
    progress: "Progress",
    students: "Students",
    posts: "Posts",
    tests: "Tests",
    tasks: "Tasks",
    addLesson: "Add lesson",
    addFile: "Add file",
    cabinet: "Cabinet",
    aboutUs_forecasting: "Development forecasting and support system",
    aboutUs_concept: "Concept of methodological competence development",
    aboutUs_rise: "Professional development courses for teachers",
    aboutUs_course: "System of course and post-course support",
    aboutUs_education: "IT-education development",
    aboutUs_practice: "Practical training",
    aboutUs_innovation: "Innovative Approach",
    aboutUs_software: "Software and educational-methodical support",
    banner1: "The concept of development of methodological competencies of teachers of IT disciplines",
    banner2: "System of course and post-course support for teachers of IT disciplines",
    banner3: "Introduction of level standards on the basis of the professional standard \"Teacher\"",
    banner4: "The system of forecasting and continuous support for the development of methodological competence of teachers",
    education: "Education",
    jobInformation: "Job information",
    generalInformation: "General information",
    email: "Email",
    birthDate: "Birth date",
    university: "University",
    universityName: "University",
    universityJobName: "University",
    graduationYear: "Graduation year",
    specialization: "Specialization",
    admissionDate: "Admission date",
    degreeAwarded: "Degree awarded",
    degree: "Degree",
    position: "Position",
    rank: "Rank",
    disciplineNames: "Disciplines",
    userNotFound: "User not found",
    courseNotFound: "Course not found",
    chatNotFound: "Chat not found",
    postCourseNotFound: "Post-Course not found",
    taskNotFound: "Task not found",
    courseFORBIDDEN: "You do not have access to this course",
    profile: "Profile",
    emailConfirm: "Email confirmation",
    save: "Save",
    send: "Send",
    create: "Create",
    firstName: "First name",
    secondName: "Second name",
    middleName: "Middle name",
    fillAllFields: "Fill in all the fields",
    admin: "Admin",
    trainer: "Trainer",
    role: "Role",
    competenceBank: "Competence Bank",
    createComponentBank: "Create Component",
    createAnketaBank: "Create Questionnaire",
    name: "Name",
    nameEng: "Name in English",
    nameKz: "Name in Kazakh",
    nameRu: "Name in Russian",
    descriptionEng: "Description in English",
    description: "Description",
    descriptionKz: "Description in Kazakh",
    descriptionRu: "Description in Russian",
    trainerUsername: "Trainer username",
    course: "Course",
    courses: "Courses",
    postCourse: "Post-Course",
    postCourses: "Post-Courses",
    coursesList: "Courses list",
    postCoursesList: "Post-Courses list",
    createCourse: "Create course",
    createPostCourse: "Create post-course",
    chooseComponent: "Choose component",
    addSection: "Add Section",
    addTask: "Add Task",
    addQuestion: "Add Question",
    delete: "Delete",
    deleteComponent: "Delete component",
    deleteQuestionnaire: "Delete questionnaire",
    sectionName: "Section name",
    question: "Question",
    answer: "Answer",
    questionType: "Question type",
    addCorrectAnswer: "Add correct answer",
    addInCorrectAnswer: "Add incorrect answer",
    createAnketaFormValidationError: "Incorrectly formed questionnaire",
    components: "Components",
    component: "Component",
    questionnaires: "Questionnaires",
    questionnaire: "Questionnaire",
    questionnaireName: "Questionnaire name",
    errorDelete: "Deletion failed",
    password: "Password",
    confirmPassword: "Confirm password",
    username: "Username",
    point: "Point",
    status: "Status",
    notStarted: "Not started",
    notSubmitted: "Not Submitted",
    submitted: "Submitted",
    submit: "Submit",
    inProgress: "In progress",
    notPassed: "Not passed",
    finished: "Finished",
    passed: "Passed",
    actions: "Actions",
    view: "View",
    submission: "Submissions",
    activate: "Activate",
    deactivate: "Deactivate",
    pass: "Pass",
    giveAnswersToAllQuestionsError: "Give answers to all questions!",
    questionnairePassed: "Questionnaire passed",
    maxPoint: "Max. point",
    numQuestions: "Number of questions",
    user: "User",
    users: "Users",
    userCreate: "Create user",
    fullName: "Full name",
    fullFilled: "Full filled",
    filled: "Filled",
    notFilled: "Not filled",
    file: "File",
    files: "Files",
    label: "Label",
    certificate: "Certificate",
    telNumber: "Phone number",
    task: "Task",
    taskName: "Task name",
    deadline: "Deadline",
    grade: "Grade",
    graded: "Graded",
    comment: "Comment",
    selectedStudent: "Selected student",
    submittedFiles: "Submitted files",
    trainingCourses: "Training Courses",
    changeProfileImage: "Change profile image",
    profileImage: "Profile image",
    profileImageHasChanged: "Profile image has changed!",
    applications: "Applications",
    application: "Application",
    createApplication: "Create application",
    applicationList: "Application list",
    confirmationMessageIsSent: "Confirmation message has been sent",
    search: "Search",
    message: "Message",
    title: "Title",
    body: "Body",
    changeStatus: "Change status",
    statusChanged: "Status changed!",
    approved: "Approved",
    notApproved: "Not approved",
    underConsideration: "Under consideration",
    awaiting: "Awaiting",
    littleCourse: 'course',
    littlePostCourse: 'post-course',
    littleTrainingCourse: 'training',
    applicationSuccessCreated: "Application created!",
    userSuccessCreated: "User created!",
    applicationErrorCreated: "Application creation failed!",
    userErrorCreated: "User creation failed!",
    roleChanged: "Role changed!",
    roleChangeFail: "Role change failed!",
    roleName: "Role name",
    analytics: "Analytics",

}

const kz = {
    aboutUs: "Біз туралы",
    education: "Білім",
    jobInformation: "Жұмыс туралы мәліметтер",
    generalInformation: "Жалпы мәліметтер",
    email: "Почта",
    birthDate: "Туған күні",
    university: "Университет",
    graduationYear: "Бітіру жылы",
    specialization: "Мамандандығы",
    admissionDate: "Түскен күні",
    degreeAwarded: "Берілген дәреже",
    degree: "Дәреже",
    position: "Позиция",
    rank: "Атағы",
    disciplineNames: "Оқытылатын пәндер",
    userNotFound: "Пайдаланушы табылмады",
    admin: "Админ",
    trainer: "Жаттықтырушы",
    role: "Рөлі",
    username: "Пайдаланушы аты",
    password: "Пароль",
    confirmPassword: "Подтвердить пароль",

}


export const lan = localStorage.getItem('lan') === "ENG" ? eng : (localStorage.getItem('lan') === "РУС" ? ru : (localStorage.getItem('lan') === "ҚАЗ" ? kz : eng))