import forecasting from "../images/forecasting-model.svg";
import concept from "../images/concept.svg";
import rise from "../images/selection-raise-symbolic.svg";
import course from "../images/e-learning-completed-course.svg";
import practice from "../images/clipboard-alt.svg";
import innovation from "../images/innovation.svg";
import software from "../images/software-layout-header-complex2.svg";

const ru = {
    aboutUs:"О Нас",
    team:"Команда",
    publications:"Публикаций",
    contacts:"Контакты",
    aboutUs_forecasting: "Система прогнозирования и поддержки развития",
    aboutUs_concept: "Концепция развития методической компетентности",
    aboutUs_rise: "Курсы повышения квалификации для преподавателей",
    aboutUs_course: "Система курсовой и посткурсовой поддержки",
    aboutUs_education: "Развитие IT-образования",
    aboutUs_practice: "Практические занятия",
    aboutUs_innovation: "Инновационный подход",
    aboutUs_software: "Программное и учебно-методическое обеспечение",
    banner1: "Концепция развития методических компетенций преподавателей IT дисциплин",
    banner2: "Система курсовой и посткурсовой поддержки преподавателей IT дисциплин",
    banner3: "Внедрение уровневых стандартов на основе профессионального стандарта \"Педагог\"",
    banner4: "Система прогнозирования и непрерывной поддержки развития методической компетенции преподавателей",
    education: "Образование",
    jobInformation: "Сведения о работе",
    generalInformation: "Общие сведения",
    email: "Почта",
    birthDate: "Дата рождения",
    university: "Унивеситет",
    graduationYear: "Год окончания",
    specialization: "Специальность",
    admissionDate: "Дата поступления",
    degreeAwarded: "Присвоенная степень",
    degree: "Степень",
    position: "Должность",
    rank: "Звание",
    disciplineNames: "Преподаваемые дисциплины",
    userNotFound: "Пользователь не найден",
}

const eng = {
    aboutUs:"About Us",
    team:"Team",
    publications:"Publications",
    contacts:"Contacts",
    levelCompetence: "Do you want to know the level of your competence?",
    projectTeam: "Project Team",
    noAccount: "I don't have an account",
    yesAccount: "I have an account",
    login: "Login",
    log_in: "Log in",
    register: "Registration",
    dashboard: "Dashboard",
    coursesAll: "All courses",
    coursesMy: "My courses",
    coursesPre: "Pre-courses",
    competenceMap: "Competence Map",
    myTasks: "My Tasks",
    chats: "Chats",
    calendar: "Calendar",
    setting: "Settings",
    logout: "Logout",
    error: "Error",
    problem: "Sorry, we have some problems",
    back: "Back",
    taskDone: "Task Done",
    lessons: "Lessons",
    students: "Students",
    posts: "Posts",
    tests: "Tests",
    tasks: "Tasks",
    addLesson: "Add lesson",
    cabinet: "Cabinet",
    aboutUs_forecasting: "Development forecasting and support system",
    aboutUs_concept: "Concept of methodological competence development",
    aboutUs_rise: "Professional development courses for teachers",
    aboutUs_course: "System of course and post-course support",
    aboutUs_education: "IT-education development",
    aboutUs_practice: "Practical training",
    aboutUs_innovation: "Innovative Approach",
    aboutUs_software: "Software and educational-methodical support",
    banner1: "The concept of development of methodological competencies of teachers of IT disciplines",
    banner2: "System of course and post-course support for teachers of IT disciplines",
    banner3: "Introduction of level standards on the basis of the professional standard \"Teacher\"",
    banner4: "The system of forecasting and continuous support for the development of methodological competence of teachers",
    education: "Education",
    jobInformation: "Job information",
    generalInformation: "General information",
    email: "Email",
    birthDate: "Birth date",
    university: "University",
    universityName: "University",
    universityJobName: "University",
    graduationYear: "Graduation year",
    specialization: "Specialization",
    admissionDate: "Admission date",
    degreeAwarded: "Degree awarded",
    degree: "Degree",
    position: "Position",
    rank: "Rank",
    disciplineNames: "Disciplines",
    userNotFound: "User not found",
    profile: "Profile",
    emailConfirm: "Email confirmation",
    save: "Save",
    create: "Create",
    firstName: "First name",
    secondName: "Second name",
    middleName: "Middle name",
    fillAllFields: "Fill in all the fields",
    admin: "Admin",
    competenceBank: "Competence Bank",
    createComponentBank: "Create Component",
    createAnketaBank: "Create Questionnaire",
    nameEng: "Name in English",
    nameKz: "Name in Kazakh",
    nameRu: "Name in Russian",
    chooseComponent: "Choose component",
    addSection: "Add Section",
    addQuestion: "Add Question",
    delete: "Delete",
    sectionName: "Section name",
    question: "Question",
    answer: "Answer",
    questionType: "Question type",
    addCorrectAnswer: "Add correct answer",
    addInCorrectAnswer: "Add incorrect answer",
    createAnketaFormValidationError: "Incorrectly formed questionnaire",

}

const kz = {
    aboutUs:"Біз туралы",
    education: "Білім",
    jobInformation: "Жұмыс туралы мәліметтер",
    generalInformation: "Жалпы мәліметтер",
    email: "Почта",
    birthDate: "Туған күні",
    university: "Университет",
    graduationYear: "Бітіру жылы",
    specialization: "Мамандандығы",
    admissionDate: "Түскен күні",
    degreeAwarded: "Берілген дәреже",
    degree: "Дәреже",
    position: "Позиция",
    rank: "Атағы",
    disciplineNames: "Оқытылатын пәндер",
    userNotFound: "Пайдаланушы табылмады",
}


export const lan = localStorage.getItem('lan') === "ENG" ? eng : (localStorage.getItem('lan') === "РУС" ? ru : (localStorage.getItem('lan') === "ҚАЗ" ? kz : eng))